### ISSUE TITLE
potential cpd issue

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ModelSEEDDatabase#28]
User submitted...

In the meantime I have found a compound entry with some possible errors: cpd11684 

This compound looks to be the same than CHEBI:16042 (http://www.ebi.ac.uk/chebi/searchId.do?chebiId=16042) or http://metacyc.org/META/NEW-IMAGE?type=COMPOUND&object=Halide-Anions

So it can be bromide, chloride, fluoride or iodide.
In consequence its mass should be unknown because is the mass of one of those 4. Not 1 for sure.
And its charge should be -1 according to ChEBI and MetaCyc.

**Comment by samseaver** [comment]
What compound? I mean, did they give you a ModelSEED identifier?

**Comment by nconrad** [comment]
whoops.  updated ticket.  It's cpd11684

**Comment by samseaver** [comment]
Yes, its mass should be unknown, and that can be updated in the database. Its charge is listed as zero because its also associated with this KEGG compound:

http://rest.kegg.jp/get/C00462

which has a formula that includes a proton.

Generally speaking however, the compound is of little concern as we cannot use it in flux balance analysis.

**Comment by samseaver** [comment]
Fixed here:

https://github.com/ModelSEED/ModelSEEDDatabase/commit/e528f4fa20e4b4833b4e695e1793a073ef32171e
