### ISSUE TITLE
Compartment question

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ModelSEEDDatabase#6]
Should all compounds in reactions have compartments?

I see "Pseudomonas aeruginosa LPS core precursor 2"  in rxn13866 doesn't:

https://www.patricbrc.org/api/model_reaction/?http_accept=application/json&eq(id,rxn13866)&select(definition)

**Comment by samseaver** [comment]
I see the problem here. This reaction came from the metabolic model iMO1053 (PA_CORE3s) and the full name of the compound is:

'Pseudomonas aeruginosa LPS core precursor 2 + KDO2-lipidA'

So the ' + ' means you're getting a parsing error, and not retrieving the full name of the compound. This occurs more than once, a quick parse gives me 25 compounds where the name itself contains a ' + ' string, such as:

'(K+ + H+)-ATPase'

I think you'll have to print the equation string using compound identifiers every time, before replacing the identifiers with the relevant names, which can be a pain, but is probably the safest way to do this. In the meantime, we can certainly consider what to do with these rogue ' + ' strings, we can simply remove the spaces so we'd get names like:

'Pseudomonas aeruginosa LPS core precursor 2+KDO2-lipidA'
'(K++H+)-ATPase'

**Comment by mmundy42** [comment]
I added modifications to the compound and reaction master.mods files to adjust the names that have embedded ' + ' strings to remove the spaces as Sam suggested.

I also found 2 reactions that had an embedded ' <=> ' and I also added a modification to remove the extra spaces.

**Comment by mmundy42** [comment]
@nconrad, are you OK with the change to remove spaces?  Just wondering if this issue can be closed.

**Comment by nconrad** [comment]
Yeah, that sounds fine.

I'm on vacation until Monday.  I'll address other tickets when I get back.
We should regroup when I get back, if possible...  And do another push on
the site.
I've made some progress that I haven't commited yet.

On Wednesday, August 19, 2015, Mike Mundy notifications@github.com wrote:

> @nconrad https://github.com/nconrad, are you OK with the change to
> remove spaces? Just wondering if this issue can be closed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ModelSEED/ModelSEEDDatabase/issues/6#issuecomment-132746317
> .

## 

---

t. 815-508-7951
e. nealconrad@gmail.com
